### ISSUE TITLE
Limit RSS feed to slider position

### ISSUE THREAD

**Issue by sublimino** [thomasdavis/gitgossip#6]
I'd like to RSS subscribe to the top 500 or fewer users. Could the feed be configurable as per the slider, or perhaps the offered in 250, 500, and 1000 versions?

**Comment by thomasdavis** [comment]
So it should only email you based off what you set on the initial slide. Not quite sure if that is what you mean.

**Comment by sublimino** [comment]
Ambition: to subscribe via RSS to 500 or less users

1) the slider restricts the number of results on https://gitgossip.com/ - it would be useful if the feed URL link dynamically respected this with a query string or similar 
2) but adding a query string etc reduces cache-/discover-abililty, so could be implemented as http://feedpress.me/gitgossip250 http://feedpress.me/gitgossip500 etc where the number corresponds to the result limiting

**Comment by thomasdavis** [comment]
Understood. I actually hack and slashed together that RSS when it launched. Is it actually working as it should?

**Comment by sublimino** [comment]
A cursory read through it in feedly showed correct "guest authors" and a
few other people subscribed, so I'd say (tentatively) yes!

**Comment by wolffc** [comment]
i like the idea of limiting RSS output. Because the output of 1000 people is quite overwhelming. please implement this features. 

by the way the feed works fine. (at least in feedly)
